spring:
  application:
    name: mod-spring-sample
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:folio}
    password: ${DB_PASSWORD:fse}
    username: ${DB_USERNAME:fse-admin}
server:
  port: 9090
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,metrics,caches,loggers,httpexchanges


